name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Berjalan pada pukul 00:00 UTC setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ghifarr1  # Ganti dengan username GitHub Anda
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'
      
      - uses: Platane/snk@master
        id: snake-dark
        with:
          github_user_name: ghifarr1  # Ganti dengan username GitHub Anda
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'yellow'
          color_snake: 'yellow'
          color_dots: '#222,#444,#11DD22,#22EE33,#33FF44'
      
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
